/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jebrixmotors;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.UIManager;

/**
 *
 * @author ibnucorp
 */
public class Loading extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form Loading
     */
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    int s=0;
    Thread th;


    /**
     * Creates new form Loading
     */
    public Loading() {
        super("Loading");
        initComponents();
        th= new Thread((Runnable)this);
    }
    
    public void setUpLoading(){
        setVisible(false);
        th.start();
    }
    
    public void run(){
        try {
            for (int i=0;i<=200;i++) {
                s=s+1;
                int m=jProgressBar1.getMaximum();
                int v=jProgressBar1.getValue();
                UIManager.put("ProgressBar.background", new Color(3, 169, 244));
                UIManager.put("ProgressBar.foreground", Color.WHITE);
                UIManager.put("ProgressBar.selectionBackground", Color.RED);
                UIManager.put("ProgressBar.selectionForeground", Color.GREEN);
                if (v<m) {
                    jProgressBar1.setValue(jProgressBar1.getValue()+1);
                } else {
                    i=201;
                    setVisible(false);
                    MainForm cb = new MainForm();
                    cb.setVisible(true);
                }
                Thread.sleep(50);
                
                
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(530, 272));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(242, 106, 106));
        jPanel2.setLayout(null);

        jProgressBar1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jProgressBar1.setForeground(new java.awt.Color(105, 153, 241));
        jProgressBar1.setStringPainted(true);
        jPanel2.add(jProgressBar1);
        jProgressBar1.setBounds(110, 120, 290, 40);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 0, 0);

        jLabel1.setFont(new java.awt.Font("Proxima Nova Th", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Memuat...");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(210, 180, 120, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(23, 0, 530, 272);

        jPanel1.setBackground(new java.awt.Color(244, 68, 68));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 279, 272);

        setSize(new java.awt.Dimension(530, 272));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loading().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
